name: Build IPA
on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer

      - name: Build and Package App
        run: |
          cd apps/ios
          xcodebuild clean build \
            -project Mural.xcodeproj \
            -scheme Mural \
            -destination "generic/platform=iOS" \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            AD_HOC_CODE_SIGNING_ALLOWED=YES \
            CONFIGURATION_BUILD_DIR=build
          
          mkdir -p Payload
          cp -r build/Mural.app Payload/
          zip -r Mural.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mural-IPA
          path: apps/ios/Mural.ipa
